### ISSUE TITLE
Unexpected token '}'

### ISSUE THREAD

**Issue by Official-Hawks** [Yonle/djs.musicbot#1]
/home/runner/VigilantIntelligentKernel/node_modules/taichi.db/lib/taichi.db.js:178
}
^

SyntaxError: Unexpected token '}'

**Comment by Yonle** [comment]
This issue is happend when Taichi.db old version was installed. We will Update it into 1.3.5 at `djs.musicbot` next Update.

**Comment by Yonle** [comment]
If you don't want to wait, Install Taichi.db v1.3.5 by executing:

`npm i taichi.db@1.3.5`

Thanks
